// server/api/login.ts
export default defineEventHandler(async (event) => {
  const https = await import('https')
  const { identity, password } = await readBody(event)

  const data = JSON.stringify({ identity, password })

  return new Promise((resolve, reject) => {
    const req = https.request(
      {
        host: 'chattryoutautogeneratedauthservice-4721.twil.io',
        method: 'POST',
        port: 443,
        path: '/login',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(data),
        },
      },
      (res) => {
        let responseData = ''
        res.on('data', (chunk) => {
          responseData += chunk
        })
        res.on('end', () => {
          resolve(responseData)
        })
      }
    )

    req.on('error', reject)
    req.write(data)
    req.end()
  })
})
